"""Submitted snapshot pipeline foundation (models, adapters, detached load, env validation, logging)."""

from ozlink_console.draft_snapshot.adapters import (
    apply_library_relative_paths,
    from_bundle_folder,
    from_canonical_json_bytes,
    from_canonical_json_dict,
    from_req_payload_dict,
)
from ozlink_console.draft_snapshot.contracts import (
    SNAPSHOT_ENGINE_VERSION_V1,
    SNAPSHOT_SCHEMA_V1,
    CanonicalMappingItem,
    CanonicalSubmittedSnapshot,
    ProposedFolderMappingItem,
    SiteLibraryContextSnapshot,
    SourceRetentionPolicy,
    new_run_id,
    new_snapshot_id,
    normalize_submitted_snapshot_id,
    parse_canonical_submitted_snapshot_dict,
    validate_canonical_required_fields,
    validate_snapshot_minimal_ready,
)
from ozlink_console.draft_snapshot.detached import (
    DetachedSubmittedSnapshot,
    load_detached_auto_bytes,
    load_detached_from_bundle_folder,
    load_detached_from_canonical_json_bytes,
    load_detached_from_canonical_json_path,
    load_detached_from_req_json_bytes,
    load_detached_from_req_json_path,
)
from ozlink_console.draft_snapshot.environment import (
    LEGACY_SNAPSHOT_ADAPTER_SOURCES,
    ConnectedEnvironmentContext,
    EnvironmentCheckResult,
    EnvironmentValidationReport,
    validate_environment_against_snapshot,
)
from ozlink_console.draft_snapshot.execution_plan_contracts import (
    ExecutionPlan,
    ExecutionPlanSummary,
    ExecutionPolicy,
    ExecutionStep,
    PlanMaterializationSummary,
    compute_execution_plan_hash,
    default_materialization_policy,
    execution_step_sort_key,
    new_execution_plan_id,
    sort_execution_steps,
    summarize_execution_plan_steps,
)
from ozlink_console.draft_snapshot.plan_materialization import (
    ResolvedSnapshotExecutionPlanBuilder,
    build_destination_chain_steps,
    build_execution_plan_from_resolved,
    subset_execution_plan_by_dependency_closure,
    subset_execution_plan_by_mapping_ids,
)
from ozlink_console.draft_snapshot.execution_bridge import (
    BridgeStepState,
    ExecutionBridgeRuntimeState,
    ExecutionPlanBridge,
)
from ozlink_console.draft_snapshot.pipeline_harness import (
    DraftPipelineHarnessRequest,
    DraftPipelineRunResult,
    bridge_runtime_state_summary,
    draft_pipeline_run_result_to_dict,
    run_draft_snapshot_pipeline,
    run_pipeline_from_bundle_folder,
    run_pipeline_from_canonical_json_bytes,
    run_pipeline_from_req_json_bytes,
)
from ozlink_console.draft_snapshot.plan_builder_interface import (
    BuildExecutionPlanRequest,
    ContractOnlyExecutionPlanBuilder,
    ExecutionPlanBuilder,
)
from ozlink_console.draft_snapshot.path_normalization import to_library_relative_path
from ozlink_console.draft_snapshot.resolution_contracts import (
    ItemResolutionResult,
    ResolvedSnapshot,
    ResolutionSummary,
    summarize_resolution,
)
from ozlink_console.draft_snapshot.resolver_service import GraphResolveIdsService, ResolveIdsService
from ozlink_console.draft_snapshot.errors import (
    SnapshotError,
    SnapshotValidationError,
    UnsupportedSnapshotVersionError,
)
from ozlink_console.draft_snapshot.run_log import (
    SnapshotPipelineEvent,
    event_from_detached_import,
    log_environment_validation_summary,
    log_pipeline_info,
    log_pipeline_warn,
    log_execution_bridge_step,
    log_harness_phase,
    log_plan_build_phase,
    log_resolution_item_state,
    validation_report_as_dict,
)

__all__ = [
    "LEGACY_SNAPSHOT_ADAPTER_SOURCES",
    "SNAPSHOT_ENGINE_VERSION_V1",
    "SNAPSHOT_SCHEMA_V1",
    "CanonicalMappingItem",
    "CanonicalSubmittedSnapshot",
    "ConnectedEnvironmentContext",
    "ContractOnlyExecutionPlanBuilder",
    "DetachedSubmittedSnapshot",
    "ExecutionPlan",
    "ExecutionPlanBuilder",
    "ExecutionPlanSummary",
    "ExecutionPolicy",
    "ExecutionStep",
    "PlanMaterializationSummary",
    "ResolvedSnapshotExecutionPlanBuilder",
    "ExecutionPlanBridge",
    "ExecutionBridgeRuntimeState",
    "BridgeStepState",
    "DraftPipelineHarnessRequest",
    "DraftPipelineRunResult",
    "bridge_runtime_state_summary",
    "draft_pipeline_run_result_to_dict",
    "run_draft_snapshot_pipeline",
    "run_pipeline_from_bundle_folder",
    "run_pipeline_from_canonical_json_bytes",
    "run_pipeline_from_req_json_bytes",
    "build_destination_chain_steps",
    "build_execution_plan_from_resolved",
    "subset_execution_plan_by_mapping_ids",
    "subset_execution_plan_by_dependency_closure",
    "compute_execution_plan_hash",
    "default_materialization_policy",
    "EnvironmentCheckResult",
    "EnvironmentValidationReport",
    "GraphResolveIdsService",
    "ItemResolutionResult",
    "ProposedFolderMappingItem",
    "ResolveIdsService",
    "ResolvedSnapshot",
    "ResolutionSummary",
    "apply_library_relative_paths",
    "BuildExecutionPlanRequest",
    "SiteLibraryContextSnapshot",
    "SourceRetentionPolicy",
    "SnapshotError",
    "SnapshotPipelineEvent",
    "SnapshotValidationError",
    "UnsupportedSnapshotVersionError",
    "event_from_detached_import",
    "from_bundle_folder",
    "from_canonical_json_bytes",
    "from_canonical_json_dict",
    "from_req_payload_dict",
    "load_detached_auto_bytes",
    "load_detached_from_bundle_folder",
    "load_detached_from_canonical_json_bytes",
    "load_detached_from_canonical_json_path",
    "load_detached_from_req_json_bytes",
    "load_detached_from_req_json_path",
    "log_environment_validation_summary",
    "log_pipeline_info",
    "log_pipeline_warn",
    "log_execution_bridge_step",
    "log_harness_phase",
    "log_plan_build_phase",
    "log_resolution_item_state",
    "new_run_id",
    "new_execution_plan_id",
    "new_snapshot_id",
    "normalize_submitted_snapshot_id",
    "parse_canonical_submitted_snapshot_dict",
    "to_library_relative_path",
    "execution_step_sort_key",
    "sort_execution_steps",
    "summarize_execution_plan_steps",
    "summarize_resolution",
    "validate_canonical_required_fields",
    "validate_environment_against_snapshot",
    "validate_snapshot_minimal_ready",
    "validation_report_as_dict",
]
